name: Mascarar Data
js_form:
    - ../../../assets/js/masks/js/jquery.meio.js
    - ../../../assets/js/masks/js/masks.js
    - ../../../../../../assets/plugins/jquery-ui/jquery-ui.min.js
    - ../../../assets/js/masks/js/datetimepicker.js
css_form:
    - ../../../../../../assets/plugins/jquery-ui/jquery-ui.css
attr:
    alt: date
    class: add-mask date-mod