name: Mascarar Data
js_form:
    - ../../../assets/js/masks/js/jquery.meio.js
    - ../../../assets/js/masks/js/masks.js
    - ../../../../../../../vendor/components/jqueryui/jquery-ui.min.js
    - ../../../assets/js/masks/js/datetimepicker.js
attr:
    alt: date
    class: add-mask date-mod
